name: Test
on: [push]
jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: clang++ -dynamiclib -framework Foundation -framework UIKit -arch arm64 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) main.cpp -o mylib.dat
      - name: Export
        uses: actions/upload-artifact@v3
        with:
          name: Result
          path: mylib.dat
